//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace HSAPI.WebReferences {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CustomServiceSoap", Namespace="http://tempuri.org/")]
    public partial class CustomService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ResponseOperationCompleted;
        
        private AuthenticationToken authenticationTokenValueField;
        
        private CustomSOAPHeader customSOAPHeaderValueField;
        
        private System.Threading.SendOrPostCallback CheckBalanceOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckDeliveryOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostServiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostService1OperationCompleted;
        
        private System.Threading.SendOrPostCallback PostService2OperationCompleted;
        
        private System.Threading.SendOrPostCallback PostService3OperationCompleted;
        
        private System.Threading.SendOrPostCallback PostService4OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetServiceOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CustomService() {
            this.Url = global::HSAPI.Properties.Settings.Default.HSAPI_QueryMgrService_QueryMgrService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public AuthenticationToken AuthenticationTokenValue {
            get {
                return this.authenticationTokenValueField;
            }
            set {
                this.authenticationTokenValueField = value;
            }
        }
        
        public CustomSOAPHeader CustomSOAPHeaderValue {
            get {
                return this.customSOAPHeaderValueField;
            }
            set {
                this.customSOAPHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ResponseCompletedEventHandler ResponseCompleted;
        
        /// <remarks/>
        public event CheckBalanceCompletedEventHandler CheckBalanceCompleted;
        
        /// <remarks/>
        public event CheckDeliveryCompletedEventHandler CheckDeliveryCompleted;
        
        /// <remarks/>
        public event PostServiceCompletedEventHandler PostServiceCompleted;
        
        /// <remarks/>
        public event PostService1CompletedEventHandler PostService1Completed;
        
        /// <remarks/>
        public event PostService2CompletedEventHandler PostService2Completed;
        
        /// <remarks/>
        public event PostService3CompletedEventHandler PostService3Completed;
        
        /// <remarks/>
        public event PostService4CompletedEventHandler PostService4Completed;
        
        /// <remarks/>
        public event GetServiceCompletedEventHandler GetServiceCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Response", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Response(string usrnm, string psswrd, string sender, string timeSent, string messageText, string shortcode) {
            object[] results = this.Invoke("Response", new object[] {
                        usrnm,
                        psswrd,
                        sender,
                        timeSent,
                        messageText,
                        shortcode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ResponseAsync(string usrnm, string psswrd, string sender, string timeSent, string messageText, string shortcode) {
            this.ResponseAsync(usrnm, psswrd, sender, timeSent, messageText, shortcode, null);
        }
        
        /// <remarks/>
        public void ResponseAsync(string usrnm, string psswrd, string sender, string timeSent, string messageText, string shortcode, object userState) {
            if ((this.ResponseOperationCompleted == null)) {
                this.ResponseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnResponseOperationCompleted);
            }
            this.InvokeAsync("Response", new object[] {
                        usrnm,
                        psswrd,
                        sender,
                        timeSent,
                        messageText,
                        shortcode}, this.ResponseOperationCompleted, userState);
        }
        
        private void OnResponseOperationCompleted(object arg) {
            if ((this.ResponseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ResponseCompleted(this, new ResponseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationTokenValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("CustomSOAPHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckBalance", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CheckBalance(string UserName) {
            object[] results = this.Invoke("CheckBalance", new object[] {
                        UserName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CheckBalanceAsync(string UserName) {
            this.CheckBalanceAsync(UserName, null);
        }
        
        /// <remarks/>
        public void CheckBalanceAsync(string UserName, object userState) {
            if ((this.CheckBalanceOperationCompleted == null)) {
                this.CheckBalanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckBalanceOperationCompleted);
            }
            this.InvokeAsync("CheckBalance", new object[] {
                        UserName}, this.CheckBalanceOperationCompleted, userState);
        }
        
        private void OnCheckBalanceOperationCompleted(object arg) {
            if ((this.CheckBalanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckBalanceCompleted(this, new CheckBalanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationTokenValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("CustomSOAPHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckDelivery", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CheckDelivery(string MessageID) {
            object[] results = this.Invoke("CheckDelivery", new object[] {
                        MessageID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CheckDeliveryAsync(string MessageID) {
            this.CheckDeliveryAsync(MessageID, null);
        }
        
        /// <remarks/>
        public void CheckDeliveryAsync(string MessageID, object userState) {
            if ((this.CheckDeliveryOperationCompleted == null)) {
                this.CheckDeliveryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckDeliveryOperationCompleted);
            }
            this.InvokeAsync("CheckDelivery", new object[] {
                        MessageID}, this.CheckDeliveryOperationCompleted, userState);
        }
        
        private void OnCheckDeliveryOperationCompleted(object arg) {
            if ((this.CheckDeliveryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckDeliveryCompleted(this, new CheckDeliveryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationTokenValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("CustomSOAPHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PostService", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PostService(string mobile, string message, string user) {
            object[] results = this.Invoke("PostService", new object[] {
                        mobile,
                        message,
                        user});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PostServiceAsync(string mobile, string message, string user) {
            this.PostServiceAsync(mobile, message, user, null);
        }
        
        /// <remarks/>
        public void PostServiceAsync(string mobile, string message, string user, object userState) {
            if ((this.PostServiceOperationCompleted == null)) {
                this.PostServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostServiceOperationCompleted);
            }
            this.InvokeAsync("PostService", new object[] {
                        mobile,
                        message,
                        user}, this.PostServiceOperationCompleted, userState);
        }
        
        private void OnPostServiceOperationCompleted(object arg) {
            if ((this.PostServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostServiceCompleted(this, new PostServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationTokenValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("CustomSOAPHeaderValue")]
        [System.Web.Services.WebMethodAttribute(MessageName="PostService1")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SMSType", RequestElementName="SMSType", RequestNamespace="http://tempuri.org/", ResponseElementName="SMSTypeResponse", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("SMSTypeResult")]
        public string PostService(string mobile, string message, string user, SMSType Type) {
            object[] results = this.Invoke("PostService1", new object[] {
                        mobile,
                        message,
                        user,
                        Type});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PostService1Async(string mobile, string message, string user, SMSType Type) {
            this.PostService1Async(mobile, message, user, Type, null);
        }
        
        /// <remarks/>
        public void PostService1Async(string mobile, string message, string user, SMSType Type, object userState) {
            if ((this.PostService1OperationCompleted == null)) {
                this.PostService1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostService1OperationCompleted);
            }
            this.InvokeAsync("PostService1", new object[] {
                        mobile,
                        message,
                        user,
                        Type}, this.PostService1OperationCompleted, userState);
        }
        
        private void OnPostService1OperationCompleted(object arg) {
            if ((this.PostService1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostService1Completed(this, new PostService1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationTokenValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("CustomSOAPHeaderValue")]
        [System.Web.Services.WebMethodAttribute(MessageName="PostService2")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SubmitType", RequestElementName="SubmitType", RequestNamespace="http://tempuri.org/", ResponseElementName="SubmitTypeResponse", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("SubmitTypeResult")]
        public string PostService(string mobile, string message, string user, SMSType Type, SubmitType sType) {
            object[] results = this.Invoke("PostService2", new object[] {
                        mobile,
                        message,
                        user,
                        Type,
                        sType});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PostService2Async(string mobile, string message, string user, SMSType Type, SubmitType sType) {
            this.PostService2Async(mobile, message, user, Type, sType, null);
        }
        
        /// <remarks/>
        public void PostService2Async(string mobile, string message, string user, SMSType Type, SubmitType sType, object userState) {
            if ((this.PostService2OperationCompleted == null)) {
                this.PostService2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostService2OperationCompleted);
            }
            this.InvokeAsync("PostService2", new object[] {
                        mobile,
                        message,
                        user,
                        Type,
                        sType}, this.PostService2OperationCompleted, userState);
        }
        
        private void OnPostService2OperationCompleted(object arg) {
            if ((this.PostService2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostService2Completed(this, new PostService2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationTokenValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("CustomSOAPHeaderValue")]
        [System.Web.Services.WebMethodAttribute(MessageName="PostService3")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Encoding", RequestElementName="Encoding", RequestNamespace="http://tempuri.org/", ResponseElementName="EncodingResponse", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("EncodingResult")]
        public string PostService(string mobile, string message, string user, SMSType Type, SubmitType sType, EncodingType eType, string UDH) {
            object[] results = this.Invoke("PostService3", new object[] {
                        mobile,
                        message,
                        user,
                        Type,
                        sType,
                        eType,
                        UDH});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PostService3Async(string mobile, string message, string user, SMSType Type, SubmitType sType, EncodingType eType, string UDH) {
            this.PostService3Async(mobile, message, user, Type, sType, eType, UDH, null);
        }
        
        /// <remarks/>
        public void PostService3Async(string mobile, string message, string user, SMSType Type, SubmitType sType, EncodingType eType, string UDH, object userState) {
            if ((this.PostService3OperationCompleted == null)) {
                this.PostService3OperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostService3OperationCompleted);
            }
            this.InvokeAsync("PostService3", new object[] {
                        mobile,
                        message,
                        user,
                        Type,
                        sType,
                        eType,
                        UDH}, this.PostService3OperationCompleted, userState);
        }
        
        private void OnPostService3OperationCompleted(object arg) {
            if ((this.PostService3Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostService3Completed(this, new PostService3CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationTokenValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("CustomSOAPHeaderValue")]
        [System.Web.Services.WebMethodAttribute(MessageName="PostService4")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Binary", RequestElementName="Binary", RequestNamespace="http://tempuri.org/", ResponseElementName="BinaryResponse", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("BinaryResult")]
        public string PostService(string mobile, string message, string user, SMSType Type, EncodingType eType, string UDH) {
            object[] results = this.Invoke("PostService4", new object[] {
                        mobile,
                        message,
                        user,
                        Type,
                        eType,
                        UDH});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PostService4Async(string mobile, string message, string user, SMSType Type, EncodingType eType, string UDH) {
            this.PostService4Async(mobile, message, user, Type, eType, UDH, null);
        }
        
        /// <remarks/>
        public void PostService4Async(string mobile, string message, string user, SMSType Type, EncodingType eType, string UDH, object userState) {
            if ((this.PostService4OperationCompleted == null)) {
                this.PostService4OperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostService4OperationCompleted);
            }
            this.InvokeAsync("PostService4", new object[] {
                        mobile,
                        message,
                        user,
                        Type,
                        eType,
                        UDH}, this.PostService4OperationCompleted, userState);
        }
        
        private void OnPostService4OperationCompleted(object arg) {
            if ((this.PostService4Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostService4Completed(this, new PostService4CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationTokenValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("CustomSOAPHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetService", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetService(string mobile, string message, string user, string pass) {
            object[] results = this.Invoke("GetService", new object[] {
                        mobile,
                        message,
                        user,
                        pass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetServiceAsync(string mobile, string message, string user, string pass) {
            this.GetServiceAsync(mobile, message, user, pass, null);
        }
        
        /// <remarks/>
        public void GetServiceAsync(string mobile, string message, string user, string pass, object userState) {
            if ((this.GetServiceOperationCompleted == null)) {
                this.GetServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetServiceOperationCompleted);
            }
            this.InvokeAsync("GetService", new object[] {
                        mobile,
                        message,
                        user,
                        pass}, this.GetServiceOperationCompleted, userState);
        }
        
        private void OnGetServiceOperationCompleted(object arg) {
            if ((this.GetServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetServiceCompleted(this, new GetServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class AuthenticationToken : System.Web.Services.Protocols.SoapHeader {
        
        private System.Guid innerTokenField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public System.Guid InnerToken {
            get {
                return this.innerTokenField;
            }
            set {
                this.innerTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class CustomSOAPHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string userNameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum SMSType {
        
        /// <remarks/>
        Normal,
        
        /// <remarks/>
        Flash,
        
        /// <remarks/>
        Zero,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum SubmitType {
        
        /// <remarks/>
        Sychronous,
        
        /// <remarks/>
        Asynchronous,
        
        /// <remarks/>
        GroupLogo,
        
        /// <remarks/>
        Ringtone,
        
        /// <remarks/>
        vCard,
        
        /// <remarks/>
        WAPPushOrMMS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum EncodingType {
        
        /// <remarks/>
        et7BitText,
        
        /// <remarks/>
        et8BitHexadecimal,
        
        /// <remarks/>
        etUCS2Text,
        
        /// <remarks/>
        etISO88591,
        
        /// <remarks/>
        etISO88595,
        
        /// <remarks/>
        etISO88598,
        
        /// <remarks/>
        etWAPPushOrMMS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ResponseCompletedEventHandler(object sender, ResponseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResponseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ResponseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CheckBalanceCompletedEventHandler(object sender, CheckBalanceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckBalanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckBalanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CheckDeliveryCompletedEventHandler(object sender, CheckDeliveryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckDeliveryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckDeliveryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void PostServiceCompletedEventHandler(object sender, PostServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void PostService1CompletedEventHandler(object sender, PostService1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostService1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostService1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void PostService2CompletedEventHandler(object sender, PostService2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostService2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostService2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void PostService3CompletedEventHandler(object sender, PostService3CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostService3CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostService3CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void PostService4CompletedEventHandler(object sender, PostService4CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostService4CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostService4CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetServiceCompletedEventHandler(object sender, GetServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591