//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSAPI.DelSubscriberMgrService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.huawei.com/bme/cbsinterface/delsubscribermgr", ConfigurationName="DelSubscriberMgrService.DelSubscriberMgr")]
    public interface DelSubscriberMgr {
        
        // CODEGEN: Generating message contract since the operation delSubscriber is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="delSubscriber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HSAPI.DelSubscriberMgrService.delSubscriberResponse delSubscriber(HSAPI.DelSubscriberMgrService.delSubscriberRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="delSubscriber", ReplyAction="*")]
        System.Threading.Tasks.Task<HSAPI.DelSubscriberMgrService.delSubscriberResponse> delSubscriberAsync(HSAPI.DelSubscriberMgrService.delSubscriberRequest1 request);
        
        // CODEGEN: Generating message contract since the operation batchDelSubscriber is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="batchDelSubscriber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HSAPI.DelSubscriberMgrService.batchDelSubscriberResponse batchDelSubscriber(HSAPI.DelSubscriberMgrService.batchDelSubscriberRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="batchDelSubscriber", ReplyAction="*")]
        System.Threading.Tasks.Task<HSAPI.DelSubscriberMgrService.batchDelSubscriberResponse> batchDelSubscriberAsync(HSAPI.DelSubscriberMgrService.batchDelSubscriberRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.huawei.com/bme/cbsinterface/delsubscribermgr")]
    public partial class DelSubscriberRequestMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RequestHeader requestHeaderField;
        
        private DelSubscriberRequest delSubscriberRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public RequestHeader RequestHeader {
            get {
                return this.requestHeaderField;
            }
            set {
                this.requestHeaderField = value;
                this.RaisePropertyChanged("RequestHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public DelSubscriberRequest DelSubscriberRequest {
            get {
                return this.delSubscriberRequestField;
            }
            set {
                this.delSubscriberRequestField = value;
                this.RaisePropertyChanged("DelSubscriberRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.huawei.com/bme/cbsinterface/common")]
    public partial class RequestHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string commandIdField;
        
        private string versionField;
        
        private string transactionIdField;
        
        private string sequenceIdField;
        
        private RequestHeaderRequestType requestTypeField;
        
        private string tenantIdField;
        
        private string languageField;
        
        private SessionEntityType sessionEntityField;
        
        private string interFromField;
        
        private string interModeField;
        
        private string interMediField;
        
        private string visitAreaField;
        
        private string currentCellField;
        
        private string additionInfoField;
        
        private string thirdPartyIDField;
        
        private string reserve2Field;
        
        private string reserve3Field;
        
        private string partnerIDField;
        
        private string operatorIDField;
        
        private string tradePartnerIDField;
        
        private string partnerOperIDField;
        
        private string belToAreaIDField;
        
        private string serialNoField;
        
        private string remarkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CommandId {
            get {
                return this.commandIdField;
            }
            set {
                this.commandIdField = value;
                this.RaisePropertyChanged("CommandId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
                this.RaisePropertyChanged("TransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SequenceId {
            get {
                return this.sequenceIdField;
            }
            set {
                this.sequenceIdField = value;
                this.RaisePropertyChanged("SequenceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public RequestHeaderRequestType RequestType {
            get {
                return this.requestTypeField;
            }
            set {
                this.requestTypeField = value;
                this.RaisePropertyChanged("RequestType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=5)]
        public string TenantId {
            get {
                return this.tenantIdField;
            }
            set {
                this.tenantIdField = value;
                this.RaisePropertyChanged("TenantId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public SessionEntityType SessionEntity {
            get {
                return this.sessionEntityField;
            }
            set {
                this.sessionEntityField = value;
                this.RaisePropertyChanged("SessionEntity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string InterFrom {
            get {
                return this.interFromField;
            }
            set {
                this.interFromField = value;
                this.RaisePropertyChanged("InterFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string InterMode {
            get {
                return this.interModeField;
            }
            set {
                this.interModeField = value;
                this.RaisePropertyChanged("InterMode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string InterMedi {
            get {
                return this.interMediField;
            }
            set {
                this.interMediField = value;
                this.RaisePropertyChanged("InterMedi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string visitArea {
            get {
                return this.visitAreaField;
            }
            set {
                this.visitAreaField = value;
                this.RaisePropertyChanged("visitArea");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string currentCell {
            get {
                return this.currentCellField;
            }
            set {
                this.currentCellField = value;
                this.RaisePropertyChanged("currentCell");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string additionInfo {
            get {
                return this.additionInfoField;
            }
            set {
                this.additionInfoField = value;
                this.RaisePropertyChanged("additionInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ThirdPartyID {
            get {
                return this.thirdPartyIDField;
            }
            set {
                this.thirdPartyIDField = value;
                this.RaisePropertyChanged("ThirdPartyID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Reserve2 {
            get {
                return this.reserve2Field;
            }
            set {
                this.reserve2Field = value;
                this.RaisePropertyChanged("Reserve2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Reserve3 {
            get {
                return this.reserve3Field;
            }
            set {
                this.reserve3Field = value;
                this.RaisePropertyChanged("Reserve3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string PartnerID {
            get {
                return this.partnerIDField;
            }
            set {
                this.partnerIDField = value;
                this.RaisePropertyChanged("PartnerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string OperatorID {
            get {
                return this.operatorIDField;
            }
            set {
                this.operatorIDField = value;
                this.RaisePropertyChanged("OperatorID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string TradePartnerID {
            get {
                return this.tradePartnerIDField;
            }
            set {
                this.tradePartnerIDField = value;
                this.RaisePropertyChanged("TradePartnerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string PartnerOperID {
            get {
                return this.partnerOperIDField;
            }
            set {
                this.partnerOperIDField = value;
                this.RaisePropertyChanged("PartnerOperID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string BelToAreaID {
            get {
                return this.belToAreaIDField;
            }
            set {
                this.belToAreaIDField = value;
                this.RaisePropertyChanged("BelToAreaID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string SerialNo {
            get {
                return this.serialNoField;
            }
            set {
                this.serialNoField = value;
                this.RaisePropertyChanged("SerialNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
                this.RaisePropertyChanged("Remark");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.huawei.com/bme/cbsinterface/common")]
    public enum RequestHeaderRequestType {
        
        /// <remarks/>
        Event,
        
        /// <remarks/>
        Start,
        
        /// <remarks/>
        Continue,
        
        /// <remarks/>
        Stop,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.huawei.com/bme/cbsinterface/common")]
    public partial class SessionEntityType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string passwordField;
        
        private string remoteAddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RemoteAddress {
            get {
                return this.remoteAddressField;
            }
            set {
                this.remoteAddressField = value;
                this.RaisePropertyChanged("RemoteAddress");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.huawei.com/bme/cbsinterface/delsubscriber")]
    public partial class BatchDelSubscriberRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fileNameField;
        
        private string taskTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("FileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TaskTime {
            get {
                return this.taskTimeField;
            }
            set {
                this.taskTimeField = value;
                this.RaisePropertyChanged("TaskTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.huawei.com/bme/cbsinterface/delsubscriber")]
    public partial class DelSubInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string subscriberNoField;
        
        private long balanceField;
        
        private bool balanceFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SubscriberNo {
            get {
                return this.subscriberNoField;
            }
            set {
                this.subscriberNoField = value;
                this.RaisePropertyChanged("SubscriberNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long Balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
                this.RaisePropertyChanged("Balance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BalanceSpecified {
            get {
                return this.balanceFieldSpecified;
            }
            set {
                this.balanceFieldSpecified = value;
                this.RaisePropertyChanged("BalanceSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.huawei.com/bme/cbsinterface/common")]
    public partial class ResultHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string commandIdField;
        
        private string versionField;
        
        private string transactionIdField;
        
        private string sequenceIdField;
        
        private string resultCodeField;
        
        private string resultDescField;
        
        private System.Nullable<long> orderIdField;
        
        private bool orderIdFieldSpecified;
        
        private string operationTimeField;
        
        private string reserve1Field;
        
        private string reserve2Field;
        
        private string reserve3Field;
        
        private string tenantIdField;
        
        private string languageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CommandId {
            get {
                return this.commandIdField;
            }
            set {
                this.commandIdField = value;
                this.RaisePropertyChanged("CommandId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
                this.RaisePropertyChanged("TransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SequenceId {
            get {
                return this.sequenceIdField;
            }
            set {
                this.sequenceIdField = value;
                this.RaisePropertyChanged("SequenceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ResultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
                this.RaisePropertyChanged("ResultCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ResultDesc {
            get {
                return this.resultDescField;
            }
            set {
                this.resultDescField = value;
                this.RaisePropertyChanged("ResultDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<long> OrderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
                this.RaisePropertyChanged("OrderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrderIdSpecified {
            get {
                return this.orderIdFieldSpecified;
            }
            set {
                this.orderIdFieldSpecified = value;
                this.RaisePropertyChanged("OrderIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string OperationTime {
            get {
                return this.operationTimeField;
            }
            set {
                this.operationTimeField = value;
                this.RaisePropertyChanged("OperationTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Reserve1 {
            get {
                return this.reserve1Field;
            }
            set {
                this.reserve1Field = value;
                this.RaisePropertyChanged("Reserve1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Reserve2 {
            get {
                return this.reserve2Field;
            }
            set {
                this.reserve2Field = value;
                this.RaisePropertyChanged("Reserve2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Reserve3 {
            get {
                return this.reserve3Field;
            }
            set {
                this.reserve3Field = value;
                this.RaisePropertyChanged("Reserve3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=11)]
        public string TenantId {
            get {
                return this.tenantIdField;
            }
            set {
                this.tenantIdField = value;
                this.RaisePropertyChanged("TenantId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.huawei.com/bme/cbsinterface/common")]
    public partial class OneTimeCharge : object, System.ComponentModel.INotifyPropertyChanged {
        
        private OneTimeChargeOneTimeFee[] toCreditField;
        
        private OneTimeChargeToBilling toBillingField;
        
        private OneTimeChargeFee2arRequestValue[] toARField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("OneTimeFee", IsNullable=false)]
        public OneTimeChargeOneTimeFee[] ToCredit {
            get {
                return this.toCreditField;
            }
            set {
                this.toCreditField = value;
                this.RaisePropertyChanged("ToCredit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public OneTimeChargeToBilling ToBilling {
            get {
                return this.toBillingField;
            }
            set {
                this.toBillingField = value;
                this.RaisePropertyChanged("ToBilling");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Fee2arRequestValue", IsNullable=false)]
        public OneTimeChargeFee2arRequestValue[] ToAR {
            get {
                return this.toARField;
            }
            set {
                this.toARField = value;
                this.RaisePropertyChanged("ToAR");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.huawei.com/bme/cbsinterface/common")]
    public partial class OneTimeChargeOneTimeFee : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int operationIDField;
        
        private bool operationIDFieldSpecified;
        
        private int subTradeTypeField;
        
        private bool subTradeTypeFieldSpecified;
        
        private int mainProductKeyField;
        
        private bool mainProductKeyFieldSpecified;
        
        private int accessModeField;
        
        private bool accessModeFieldSpecified;
        
        private int productKeyField;
        
        private bool productKeyFieldSpecified;
        
        private long chargeAmountField;
        
        private bool chargeAmountFieldSpecified;
        
        private string subscriberNoField;
        
        private string accountCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int OperationID {
            get {
                return this.operationIDField;
            }
            set {
                this.operationIDField = value;
                this.RaisePropertyChanged("OperationID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OperationIDSpecified {
            get {
                return this.operationIDFieldSpecified;
            }
            set {
                this.operationIDFieldSpecified = value;
                this.RaisePropertyChanged("OperationIDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int SubTradeType {
            get {
                return this.subTradeTypeField;
            }
            set {
                this.subTradeTypeField = value;
                this.RaisePropertyChanged("SubTradeType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SubTradeTypeSpecified {
            get {
                return this.subTradeTypeFieldSpecified;
            }
            set {
                this.subTradeTypeFieldSpecified = value;
                this.RaisePropertyChanged("SubTradeTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int MainProductKey {
            get {
                return this.mainProductKeyField;
            }
            set {
                this.mainProductKeyField = value;
                this.RaisePropertyChanged("MainProductKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MainProductKeySpecified {
            get {
                return this.mainProductKeyFieldSpecified;
            }
            set {
                this.mainProductKeyFieldSpecified = value;
                this.RaisePropertyChanged("MainProductKeySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int AccessMode {
            get {
                return this.accessModeField;
            }
            set {
                this.accessModeField = value;
                this.RaisePropertyChanged("AccessMode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AccessModeSpecified {
            get {
                return this.accessModeFieldSpecified;
            }
            set {
                this.accessModeFieldSpecified = value;
                this.RaisePropertyChanged("AccessModeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int ProductKey {
            get {
                return this.productKeyField;
            }
            set {
                this.productKeyField = value;
                this.RaisePropertyChanged("ProductKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProductKeySpecified {
            get {
                return this.productKeyFieldSpecified;
            }
            set {
                this.productKeyFieldSpecified = value;
                this.RaisePropertyChanged("ProductKeySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long ChargeAmount {
            get {
                return this.chargeAmountField;
            }
            set {
                this.chargeAmountField = value;
                this.RaisePropertyChanged("ChargeAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ChargeAmountSpecified {
            get {
                return this.chargeAmountFieldSpecified;
            }
            set {
                this.chargeAmountFieldSpecified = value;
                this.RaisePropertyChanged("ChargeAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string SubscriberNo {
            get {
                return this.subscriberNoField;
            }
            set {
                this.subscriberNoField = value;
                this.RaisePropertyChanged("SubscriberNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string AccountCode {
            get {
                return this.accountCodeField;
            }
            set {
                this.accountCodeField = value;
                this.RaisePropertyChanged("AccountCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.huawei.com/bme/cbsinterface/common")]
    public partial class OneTimeChargeToBilling : object, System.ComponentModel.INotifyPropertyChanged {
        
        private OneTimeChargeToBillingSubFeeValue[] subFeeListField;
        
        private string busiTypeField;
        
        private string bsnoField;
        
        private string channelIdField;
        
        private string remarkField;
        
        private string tradeTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("SubFeeValue", IsNullable=false)]
        public OneTimeChargeToBillingSubFeeValue[] SubFeeList {
            get {
                return this.subFeeListField;
            }
            set {
                this.subFeeListField = value;
                this.RaisePropertyChanged("SubFeeList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string BusiType {
            get {
                return this.busiTypeField;
            }
            set {
                this.busiTypeField = value;
                this.RaisePropertyChanged("BusiType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Bsno {
            get {
                return this.bsnoField;
            }
            set {
                this.bsnoField = value;
                this.RaisePropertyChanged("Bsno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ChannelId {
            get {
                return this.channelIdField;
            }
            set {
                this.channelIdField = value;
                this.RaisePropertyChanged("ChannelId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
                this.RaisePropertyChanged("Remark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string TradeTime {
            get {
                return this.tradeTimeField;
            }
            set {
                this.tradeTimeField = value;
                this.RaisePropertyChanged("TradeTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.huawei.com/bme/cbsinterface/common")]
    public partial class OneTimeChargeToBillingSubFeeValue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string acctIdField;
        
        private string subIdField;
        
        private OneTimeChargeToBillingSubFeeValueItemValue[] itemListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AcctId {
            get {
                return this.acctIdField;
            }
            set {
                this.acctIdField = value;
                this.RaisePropertyChanged("AcctId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SubId {
            get {
                return this.subIdField;
            }
            set {
                this.subIdField = value;
                this.RaisePropertyChanged("SubId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ItemValue", IsNullable=false)]
        public OneTimeChargeToBillingSubFeeValueItemValue[] ItemList {
            get {
                return this.itemListField;
            }
            set {
                this.itemListField = value;
                this.RaisePropertyChanged("ItemList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.huawei.com/bme/cbsinterface/common")]
    public partial class OneTimeChargeToBillingSubFeeValueItemValue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string itemIdField;
        
        private long amountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ItemId {
            get {
                return this.itemIdField;
            }
            set {
                this.itemIdField = value;
                this.RaisePropertyChanged("ItemId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.huawei.com/bme/cbsinterface/common")]
    public partial class OneTimeChargeFee2arRequestValue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string acctIdField;
        
        private string acctCodeField;
        
        private string custIdField;
        
        private string custCodeField;
        
        private string subIdField;
        
        private string msisdnField;
        
        private string teleTypeField;
        
        private string invoiceDateField;
        
        private string dueDateField;
        
        private string busiTypeField;
        
        private string bsnoField;
        
        private string isCustomerField;
        
        private string channelIdField;
        
        private string remarkField;
        
        private OneTimeChargeFee2arRequestValueFee2arRequestDetailValue[] fee2arRequestDetailListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AcctId {
            get {
                return this.acctIdField;
            }
            set {
                this.acctIdField = value;
                this.RaisePropertyChanged("AcctId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AcctCode {
            get {
                return this.acctCodeField;
            }
            set {
                this.acctCodeField = value;
                this.RaisePropertyChanged("AcctCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CustId {
            get {
                return this.custIdField;
            }
            set {
                this.custIdField = value;
                this.RaisePropertyChanged("CustId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CustCode {
            get {
                return this.custCodeField;
            }
            set {
                this.custCodeField = value;
                this.RaisePropertyChanged("CustCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SubId {
            get {
                return this.subIdField;
            }
            set {
                this.subIdField = value;
                this.RaisePropertyChanged("SubId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Msisdn {
            get {
                return this.msisdnField;
            }
            set {
                this.msisdnField = value;
                this.RaisePropertyChanged("Msisdn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string TeleType {
            get {
                return this.teleTypeField;
            }
            set {
                this.teleTypeField = value;
                this.RaisePropertyChanged("TeleType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string InvoiceDate {
            get {
                return this.invoiceDateField;
            }
            set {
                this.invoiceDateField = value;
                this.RaisePropertyChanged("InvoiceDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string DueDate {
            get {
                return this.dueDateField;
            }
            set {
                this.dueDateField = value;
                this.RaisePropertyChanged("DueDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string BusiType {
            get {
                return this.busiTypeField;
            }
            set {
                this.busiTypeField = value;
                this.RaisePropertyChanged("BusiType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Bsno {
            get {
                return this.bsnoField;
            }
            set {
                this.bsnoField = value;
                this.RaisePropertyChanged("Bsno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string isCustomer {
            get {
                return this.isCustomerField;
            }
            set {
                this.isCustomerField = value;
                this.RaisePropertyChanged("isCustomer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string ChannelId {
            get {
                return this.channelIdField;
            }
            set {
                this.channelIdField = value;
                this.RaisePropertyChanged("ChannelId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
                this.RaisePropertyChanged("Remark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=14)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Fee2arRequestDetailValue", IsNullable=false)]
        public OneTimeChargeFee2arRequestValueFee2arRequestDetailValue[] Fee2arRequestDetailList {
            get {
                return this.fee2arRequestDetailListField;
            }
            set {
                this.fee2arRequestDetailListField = value;
                this.RaisePropertyChanged("Fee2arRequestDetailList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.huawei.com/bme/cbsinterface/common")]
    public partial class OneTimeChargeFee2arRequestValueFee2arRequestDetailValue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string transTypeField;
        
        private string productNameField;
        
        private long orderQtyField;
        
        private long backQtyField;
        
        private long salesQtyField;
        
        private long unitPriceField;
        
        private long chargeField;
        
        private long discountAmtField;
        
        private string transDateField;
        
        private string salesDateField;
        
        private string feeItemCodeField;
        
        private string billCycleIdField;
        
        private string taxInclusiveField;
        
        private string glacodeField;
        
        private string waiveGlCodeField;
        
        private string rebateGlcodeField;
        
        private long rebateAmtField;
        
        private bool rebateAmtFieldSpecified;
        
        private string resTypeIdField;
        
        private string resModelIdField;
        
        private string resIdField;
        
        private string resCodeField;
        
        private long resAmoutField;
        
        private bool resAmoutFieldSpecified;
        
        private string refNoField;
        
        private string feeTypeField;
        
        private string productIdField;
        
        private string spCpIdField;
        
        private string serviceIdField;
        
        private string prmFlagField;
        
        private string serviceTypeField;
        
        private string serviceCategoryField;
        
        private string reasonCodeField;
        
        private string feeSubTypeField;
        
        private string invoiceTypeField;
        
        private string remarkField;
        
        /// <remarks/>
        public string transType {
            get {
                return this.transTypeField;
            }
            set {
                this.transTypeField = value;
                this.RaisePropertyChanged("transType");
            }
        }
        
        /// <remarks/>
        public string productName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
                this.RaisePropertyChanged("productName");
            }
        }
        
        /// <remarks/>
        public long orderQty {
            get {
                return this.orderQtyField;
            }
            set {
                this.orderQtyField = value;
                this.RaisePropertyChanged("orderQty");
            }
        }
        
        /// <remarks/>
        public long backQty {
            get {
                return this.backQtyField;
            }
            set {
                this.backQtyField = value;
                this.RaisePropertyChanged("backQty");
            }
        }
        
        /// <remarks/>
        public long salesQty {
            get {
                return this.salesQtyField;
            }
            set {
                this.salesQtyField = value;
                this.RaisePropertyChanged("salesQty");
            }
        }
        
        /// <remarks/>
        public long unitPrice {
            get {
                return this.unitPriceField;
            }
            set {
                this.unitPriceField = value;
                this.RaisePropertyChanged("unitPrice");
            }
        }
        
        /// <remarks/>
        public long charge {
            get {
                return this.chargeField;
            }
            set {
                this.chargeField = value;
                this.RaisePropertyChanged("charge");
            }
        }
        
        /// <remarks/>
        public long discountAmt {
            get {
                return this.discountAmtField;
            }
            set {
                this.discountAmtField = value;
                this.RaisePropertyChanged("discountAmt");
            }
        }
        
        /// <remarks/>
        public string transDate {
            get {
                return this.transDateField;
            }
            set {
                this.transDateField = value;
                this.RaisePropertyChanged("transDate");
            }
        }
        
        /// <remarks/>
        public string salesDate {
            get {
                return this.salesDateField;
            }
            set {
                this.salesDateField = value;
                this.RaisePropertyChanged("salesDate");
            }
        }
        
        /// <remarks/>
        public string feeItemCode {
            get {
                return this.feeItemCodeField;
            }
            set {
                this.feeItemCodeField = value;
                this.RaisePropertyChanged("feeItemCode");
            }
        }
        
        /// <remarks/>
        public string billCycleId {
            get {
                return this.billCycleIdField;
            }
            set {
                this.billCycleIdField = value;
                this.RaisePropertyChanged("billCycleId");
            }
        }
        
        /// <remarks/>
        public string taxInclusive {
            get {
                return this.taxInclusiveField;
            }
            set {
                this.taxInclusiveField = value;
                this.RaisePropertyChanged("taxInclusive");
            }
        }
        
        /// <remarks/>
        public string glacode {
            get {
                return this.glacodeField;
            }
            set {
                this.glacodeField = value;
                this.RaisePropertyChanged("glacode");
            }
        }
        
        /// <remarks/>
        public string waiveGlCode {
            get {
                return this.waiveGlCodeField;
            }
            set {
                this.waiveGlCodeField = value;
                this.RaisePropertyChanged("waiveGlCode");
            }
        }
        
        /// <remarks/>
        public string rebateGlcode {
            get {
                return this.rebateGlcodeField;
            }
            set {
                this.rebateGlcodeField = value;
                this.RaisePropertyChanged("rebateGlcode");
            }
        }
        
        /// <remarks/>
        public long rebateAmt {
            get {
                return this.rebateAmtField;
            }
            set {
                this.rebateAmtField = value;
                this.RaisePropertyChanged("rebateAmt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rebateAmtSpecified {
            get {
                return this.rebateAmtFieldSpecified;
            }
            set {
                this.rebateAmtFieldSpecified = value;
                this.RaisePropertyChanged("rebateAmtSpecified");
            }
        }
        
        /// <remarks/>
        public string resTypeId {
            get {
                return this.resTypeIdField;
            }
            set {
                this.resTypeIdField = value;
                this.RaisePropertyChanged("resTypeId");
            }
        }
        
        /// <remarks/>
        public string resModelId {
            get {
                return this.resModelIdField;
            }
            set {
                this.resModelIdField = value;
                this.RaisePropertyChanged("resModelId");
            }
        }
        
        /// <remarks/>
        public string resId {
            get {
                return this.resIdField;
            }
            set {
                this.resIdField = value;
                this.RaisePropertyChanged("resId");
            }
        }
        
        /// <remarks/>
        public string resCode {
            get {
                return this.resCodeField;
            }
            set {
                this.resCodeField = value;
                this.RaisePropertyChanged("resCode");
            }
        }
        
        /// <remarks/>
        public long resAmout {
            get {
                return this.resAmoutField;
            }
            set {
                this.resAmoutField = value;
                this.RaisePropertyChanged("resAmout");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resAmoutSpecified {
            get {
                return this.resAmoutFieldSpecified;
            }
            set {
                this.resAmoutFieldSpecified = value;
                this.RaisePropertyChanged("resAmoutSpecified");
            }
        }
        
        /// <remarks/>
        public string refNo {
            get {
                return this.refNoField;
            }
            set {
                this.refNoField = value;
                this.RaisePropertyChanged("refNo");
            }
        }
        
        /// <remarks/>
        public string feeType {
            get {
                return this.feeTypeField;
            }
            set {
                this.feeTypeField = value;
                this.RaisePropertyChanged("feeType");
            }
        }
        
        /// <remarks/>
        public string productId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
                this.RaisePropertyChanged("productId");
            }
        }
        
        /// <remarks/>
        public string spCpId {
            get {
                return this.spCpIdField;
            }
            set {
                this.spCpIdField = value;
                this.RaisePropertyChanged("spCpId");
            }
        }
        
        /// <remarks/>
        public string serviceId {
            get {
                return this.serviceIdField;
            }
            set {
                this.serviceIdField = value;
                this.RaisePropertyChanged("serviceId");
            }
        }
        
        /// <remarks/>
        public string prmFlag {
            get {
                return this.prmFlagField;
            }
            set {
                this.prmFlagField = value;
                this.RaisePropertyChanged("prmFlag");
            }
        }
        
        /// <remarks/>
        public string serviceType {
            get {
                return this.serviceTypeField;
            }
            set {
                this.serviceTypeField = value;
                this.RaisePropertyChanged("serviceType");
            }
        }
        
        /// <remarks/>
        public string serviceCategory {
            get {
                return this.serviceCategoryField;
            }
            set {
                this.serviceCategoryField = value;
                this.RaisePropertyChanged("serviceCategory");
            }
        }
        
        /// <remarks/>
        public string reasonCode {
            get {
                return this.reasonCodeField;
            }
            set {
                this.reasonCodeField = value;
                this.RaisePropertyChanged("reasonCode");
            }
        }
        
        /// <remarks/>
        public string feeSubType {
            get {
                return this.feeSubTypeField;
            }
            set {
                this.feeSubTypeField = value;
                this.RaisePropertyChanged("feeSubType");
            }
        }
        
        /// <remarks/>
        public string invoiceType {
            get {
                return this.invoiceTypeField;
            }
            set {
                this.invoiceTypeField = value;
                this.RaisePropertyChanged("invoiceType");
            }
        }
        
        /// <remarks/>
        public string remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
                this.RaisePropertyChanged("remark");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.huawei.com/bme/cbsinterface/delsubscriber")]
    public partial class DelSubscriberRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string subscriberNoField;
        
        private OneTimeCharge oneTimeChargeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SubscriberNo {
            get {
                return this.subscriberNoField;
            }
            set {
                this.subscriberNoField = value;
                this.RaisePropertyChanged("SubscriberNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public OneTimeCharge OneTimeCharge {
            get {
                return this.oneTimeChargeField;
            }
            set {
                this.oneTimeChargeField = value;
                this.RaisePropertyChanged("OneTimeCharge");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.huawei.com/bme/cbsinterface/delsubscribermgr")]
    public partial class DelSubscriberResultMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultHeader resultHeaderField;
        
        private DelSubInfo[] delSubscriberResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultHeader ResultHeader {
            get {
                return this.resultHeaderField;
            }
            set {
                this.resultHeaderField = value;
                this.RaisePropertyChanged("ResultHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DelSubInfoList", Namespace="http://www.huawei.com/bme/cbsinterface/delsubscriber", IsNullable=false)]
        public DelSubInfo[] DelSubscriberResult {
            get {
                return this.delSubscriberResultField;
            }
            set {
                this.delSubscriberResultField = value;
                this.RaisePropertyChanged("DelSubscriberResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class delSubscriberRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.huawei.com/bme/cbsinterface/delsubscribermgr", Order=0)]
        public HSAPI.DelSubscriberMgrService.DelSubscriberRequestMsg DelSubscriberRequestMsg;
        
        public delSubscriberRequest1() {
        }
        
        public delSubscriberRequest1(HSAPI.DelSubscriberMgrService.DelSubscriberRequestMsg DelSubscriberRequestMsg) {
            this.DelSubscriberRequestMsg = DelSubscriberRequestMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class delSubscriberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.huawei.com/bme/cbsinterface/delsubscribermgr", Order=0)]
        public HSAPI.DelSubscriberMgrService.DelSubscriberResultMsg DelSubscriberResultMsg;
        
        public delSubscriberResponse() {
        }
        
        public delSubscriberResponse(HSAPI.DelSubscriberMgrService.DelSubscriberResultMsg DelSubscriberResultMsg) {
            this.DelSubscriberResultMsg = DelSubscriberResultMsg;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.huawei.com/bme/cbsinterface/delsubscribermgr")]
    public partial class BatchDelSubscriberRequestMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RequestHeader requestHeaderField;
        
        private BatchDelSubscriberRequest batchDelSubscriberRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public RequestHeader RequestHeader {
            get {
                return this.requestHeaderField;
            }
            set {
                this.requestHeaderField = value;
                this.RaisePropertyChanged("RequestHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public BatchDelSubscriberRequest BatchDelSubscriberRequest {
            get {
                return this.batchDelSubscriberRequestField;
            }
            set {
                this.batchDelSubscriberRequestField = value;
                this.RaisePropertyChanged("BatchDelSubscriberRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.huawei.com/bme/cbsinterface/delsubscribermgr")]
    public partial class BatchDelSubscriberResultMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultHeader resultHeaderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultHeader ResultHeader {
            get {
                return this.resultHeaderField;
            }
            set {
                this.resultHeaderField = value;
                this.RaisePropertyChanged("ResultHeader");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class batchDelSubscriberRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.huawei.com/bme/cbsinterface/delsubscribermgr", Order=0)]
        public HSAPI.DelSubscriberMgrService.BatchDelSubscriberRequestMsg BatchDelSubscriberRequestMsg;
        
        public batchDelSubscriberRequest1() {
        }
        
        public batchDelSubscriberRequest1(HSAPI.DelSubscriberMgrService.BatchDelSubscriberRequestMsg BatchDelSubscriberRequestMsg) {
            this.BatchDelSubscriberRequestMsg = BatchDelSubscriberRequestMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class batchDelSubscriberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.huawei.com/bme/cbsinterface/delsubscribermgr", Order=0)]
        public HSAPI.DelSubscriberMgrService.BatchDelSubscriberResultMsg BatchDelSubscriberResultMsg;
        
        public batchDelSubscriberResponse() {
        }
        
        public batchDelSubscriberResponse(HSAPI.DelSubscriberMgrService.BatchDelSubscriberResultMsg BatchDelSubscriberResultMsg) {
            this.BatchDelSubscriberResultMsg = BatchDelSubscriberResultMsg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DelSubscriberMgrChannel : HSAPI.DelSubscriberMgrService.DelSubscriberMgr, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DelSubscriberMgrClient : System.ServiceModel.ClientBase<HSAPI.DelSubscriberMgrService.DelSubscriberMgr>, HSAPI.DelSubscriberMgrService.DelSubscriberMgr {
        
        public DelSubscriberMgrClient() {
        }
        
        public DelSubscriberMgrClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DelSubscriberMgrClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DelSubscriberMgrClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DelSubscriberMgrClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HSAPI.DelSubscriberMgrService.delSubscriberResponse HSAPI.DelSubscriberMgrService.DelSubscriberMgr.delSubscriber(HSAPI.DelSubscriberMgrService.delSubscriberRequest1 request) {
            return base.Channel.delSubscriber(request);
        }
        
        public HSAPI.DelSubscriberMgrService.DelSubscriberResultMsg delSubscriber(HSAPI.DelSubscriberMgrService.DelSubscriberRequestMsg DelSubscriberRequestMsg) {
            HSAPI.DelSubscriberMgrService.delSubscriberRequest1 inValue = new HSAPI.DelSubscriberMgrService.delSubscriberRequest1();
            inValue.DelSubscriberRequestMsg = DelSubscriberRequestMsg;
            HSAPI.DelSubscriberMgrService.delSubscriberResponse retVal = ((HSAPI.DelSubscriberMgrService.DelSubscriberMgr)(this)).delSubscriber(inValue);
            return retVal.DelSubscriberResultMsg;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HSAPI.DelSubscriberMgrService.delSubscriberResponse> HSAPI.DelSubscriberMgrService.DelSubscriberMgr.delSubscriberAsync(HSAPI.DelSubscriberMgrService.delSubscriberRequest1 request) {
            return base.Channel.delSubscriberAsync(request);
        }
        
        public System.Threading.Tasks.Task<HSAPI.DelSubscriberMgrService.delSubscriberResponse> delSubscriberAsync(HSAPI.DelSubscriberMgrService.DelSubscriberRequestMsg DelSubscriberRequestMsg) {
            HSAPI.DelSubscriberMgrService.delSubscriberRequest1 inValue = new HSAPI.DelSubscriberMgrService.delSubscriberRequest1();
            inValue.DelSubscriberRequestMsg = DelSubscriberRequestMsg;
            return ((HSAPI.DelSubscriberMgrService.DelSubscriberMgr)(this)).delSubscriberAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HSAPI.DelSubscriberMgrService.batchDelSubscriberResponse HSAPI.DelSubscriberMgrService.DelSubscriberMgr.batchDelSubscriber(HSAPI.DelSubscriberMgrService.batchDelSubscriberRequest1 request) {
            return base.Channel.batchDelSubscriber(request);
        }
        
        public HSAPI.DelSubscriberMgrService.BatchDelSubscriberResultMsg batchDelSubscriber(HSAPI.DelSubscriberMgrService.BatchDelSubscriberRequestMsg BatchDelSubscriberRequestMsg) {
            HSAPI.DelSubscriberMgrService.batchDelSubscriberRequest1 inValue = new HSAPI.DelSubscriberMgrService.batchDelSubscriberRequest1();
            inValue.BatchDelSubscriberRequestMsg = BatchDelSubscriberRequestMsg;
            HSAPI.DelSubscriberMgrService.batchDelSubscriberResponse retVal = ((HSAPI.DelSubscriberMgrService.DelSubscriberMgr)(this)).batchDelSubscriber(inValue);
            return retVal.BatchDelSubscriberResultMsg;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HSAPI.DelSubscriberMgrService.batchDelSubscriberResponse> HSAPI.DelSubscriberMgrService.DelSubscriberMgr.batchDelSubscriberAsync(HSAPI.DelSubscriberMgrService.batchDelSubscriberRequest1 request) {
            return base.Channel.batchDelSubscriberAsync(request);
        }
        
        public System.Threading.Tasks.Task<HSAPI.DelSubscriberMgrService.batchDelSubscriberResponse> batchDelSubscriberAsync(HSAPI.DelSubscriberMgrService.BatchDelSubscriberRequestMsg BatchDelSubscriberRequestMsg) {
            HSAPI.DelSubscriberMgrService.batchDelSubscriberRequest1 inValue = new HSAPI.DelSubscriberMgrService.batchDelSubscriberRequest1();
            inValue.BatchDelSubscriberRequestMsg = BatchDelSubscriberRequestMsg;
            return ((HSAPI.DelSubscriberMgrService.DelSubscriberMgr)(this)).batchDelSubscriberAsync(inValue);
        }
    }
}
