//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSAPI.PasswordMgrService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.huawei.com/bme/cbsinterface/passwordmgr", ConfigurationName="PasswordMgrService.Password")]
    public interface Password {
        
        // CODEGEN: Generating message contract since the operation CheckPassword is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="CheckPassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HSAPI.PasswordMgrService.CheckPasswordResponse CheckPassword(HSAPI.PasswordMgrService.CheckPasswordRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="CheckPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<HSAPI.PasswordMgrService.CheckPasswordResponse> CheckPasswordAsync(HSAPI.PasswordMgrService.CheckPasswordRequest1 request);
        
        // CODEGEN: Generating message contract since the operation ChangePassword is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="ChangePassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HSAPI.PasswordMgrService.ChangePasswordResponse ChangePassword(HSAPI.PasswordMgrService.ChangePasswordRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="ChangePassword", ReplyAction="*")]
        System.Threading.Tasks.Task<HSAPI.PasswordMgrService.ChangePasswordResponse> ChangePasswordAsync(HSAPI.PasswordMgrService.ChangePasswordRequest1 request);
        
        // CODEGEN: Generating message contract since the operation ResetPassword is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="ResetPassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HSAPI.PasswordMgrService.ResetPasswordResponse ResetPassword(HSAPI.PasswordMgrService.ResetPasswordRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="ResetPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<HSAPI.PasswordMgrService.ResetPasswordResponse> ResetPasswordAsync(HSAPI.PasswordMgrService.ResetPasswordRequest1 request);
        
        // CODEGEN: Generating message contract since the operation CheckOperatorPassword is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="CheckOperatorPassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HSAPI.PasswordMgrService.CheckOperatorPasswordResponse CheckOperatorPassword(HSAPI.PasswordMgrService.CheckOperatorPasswordRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="CheckOperatorPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<HSAPI.PasswordMgrService.CheckOperatorPasswordResponse> CheckOperatorPasswordAsync(HSAPI.PasswordMgrService.CheckOperatorPasswordRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.huawei.com/bme/cbsinterface/passwordmgr")]
    public partial class CheckPasswordRequestMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RequestHeader requestHeaderField;
        
        private CheckPasswordRequest checkPasswordRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public RequestHeader RequestHeader {
            get {
                return this.requestHeaderField;
            }
            set {
                this.requestHeaderField = value;
                this.RaisePropertyChanged("RequestHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public CheckPasswordRequest CheckPasswordRequest {
            get {
                return this.checkPasswordRequestField;
            }
            set {
                this.checkPasswordRequestField = value;
                this.RaisePropertyChanged("CheckPasswordRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.huawei.com/bme/cbsinterface/common")]
    public partial class RequestHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string commandIdField;
        
        private string versionField;
        
        private string transactionIdField;
        
        private string sequenceIdField;
        
        private RequestHeaderRequestType requestTypeField;
        
        private string tenantIdField;
        
        private string languageField;
        
        private SessionEntityType sessionEntityField;
        
        private string interFromField;
        
        private string interModeField;
        
        private string interMediField;
        
        private string visitAreaField;
        
        private string currentCellField;
        
        private string additionInfoField;
        
        private string thirdPartyIDField;
        
        private string reserve2Field;
        
        private string reserve3Field;
        
        private string partnerIDField;
        
        private string operatorIDField;
        
        private string tradePartnerIDField;
        
        private string partnerOperIDField;
        
        private string belToAreaIDField;
        
        private string serialNoField;
        
        private string remarkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CommandId {
            get {
                return this.commandIdField;
            }
            set {
                this.commandIdField = value;
                this.RaisePropertyChanged("CommandId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
                this.RaisePropertyChanged("TransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SequenceId {
            get {
                return this.sequenceIdField;
            }
            set {
                this.sequenceIdField = value;
                this.RaisePropertyChanged("SequenceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public RequestHeaderRequestType RequestType {
            get {
                return this.requestTypeField;
            }
            set {
                this.requestTypeField = value;
                this.RaisePropertyChanged("RequestType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=5)]
        public string TenantId {
            get {
                return this.tenantIdField;
            }
            set {
                this.tenantIdField = value;
                this.RaisePropertyChanged("TenantId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public SessionEntityType SessionEntity {
            get {
                return this.sessionEntityField;
            }
            set {
                this.sessionEntityField = value;
                this.RaisePropertyChanged("SessionEntity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string InterFrom {
            get {
                return this.interFromField;
            }
            set {
                this.interFromField = value;
                this.RaisePropertyChanged("InterFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string InterMode {
            get {
                return this.interModeField;
            }
            set {
                this.interModeField = value;
                this.RaisePropertyChanged("InterMode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string InterMedi {
            get {
                return this.interMediField;
            }
            set {
                this.interMediField = value;
                this.RaisePropertyChanged("InterMedi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string visitArea {
            get {
                return this.visitAreaField;
            }
            set {
                this.visitAreaField = value;
                this.RaisePropertyChanged("visitArea");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string currentCell {
            get {
                return this.currentCellField;
            }
            set {
                this.currentCellField = value;
                this.RaisePropertyChanged("currentCell");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string additionInfo {
            get {
                return this.additionInfoField;
            }
            set {
                this.additionInfoField = value;
                this.RaisePropertyChanged("additionInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ThirdPartyID {
            get {
                return this.thirdPartyIDField;
            }
            set {
                this.thirdPartyIDField = value;
                this.RaisePropertyChanged("ThirdPartyID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Reserve2 {
            get {
                return this.reserve2Field;
            }
            set {
                this.reserve2Field = value;
                this.RaisePropertyChanged("Reserve2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Reserve3 {
            get {
                return this.reserve3Field;
            }
            set {
                this.reserve3Field = value;
                this.RaisePropertyChanged("Reserve3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string PartnerID {
            get {
                return this.partnerIDField;
            }
            set {
                this.partnerIDField = value;
                this.RaisePropertyChanged("PartnerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string OperatorID {
            get {
                return this.operatorIDField;
            }
            set {
                this.operatorIDField = value;
                this.RaisePropertyChanged("OperatorID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string TradePartnerID {
            get {
                return this.tradePartnerIDField;
            }
            set {
                this.tradePartnerIDField = value;
                this.RaisePropertyChanged("TradePartnerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string PartnerOperID {
            get {
                return this.partnerOperIDField;
            }
            set {
                this.partnerOperIDField = value;
                this.RaisePropertyChanged("PartnerOperID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string BelToAreaID {
            get {
                return this.belToAreaIDField;
            }
            set {
                this.belToAreaIDField = value;
                this.RaisePropertyChanged("BelToAreaID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string SerialNo {
            get {
                return this.serialNoField;
            }
            set {
                this.serialNoField = value;
                this.RaisePropertyChanged("SerialNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
                this.RaisePropertyChanged("Remark");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.huawei.com/bme/cbsinterface/common")]
    public enum RequestHeaderRequestType {
        
        /// <remarks/>
        Event,
        
        /// <remarks/>
        Start,
        
        /// <remarks/>
        Continue,
        
        /// <remarks/>
        Stop,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.huawei.com/bme/cbsinterface/common")]
    public partial class SessionEntityType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string passwordField;
        
        private string remoteAddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RemoteAddress {
            get {
                return this.remoteAddressField;
            }
            set {
                this.remoteAddressField = value;
                this.RaisePropertyChanged("RemoteAddress");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.huawei.com/bme/cbsinterface/password")]
    public partial class CheckOperatorPasswordRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string operatorIdField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string OperatorId {
            get {
                return this.operatorIdField;
            }
            set {
                this.operatorIdField = value;
                this.RaisePropertyChanged("OperatorId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.huawei.com/bme/cbsinterface/password")]
    public partial class ResetPasswordRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string subscriberNoField;
        
        private string newPasswordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SubscriberNo {
            get {
                return this.subscriberNoField;
            }
            set {
                this.subscriberNoField = value;
                this.RaisePropertyChanged("SubscriberNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NewPassword {
            get {
                return this.newPasswordField;
            }
            set {
                this.newPasswordField = value;
                this.RaisePropertyChanged("NewPassword");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.huawei.com/bme/cbsinterface/password")]
    public partial class ChangePasswordRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string subscriberNoField;
        
        private string oldPasswordField;
        
        private string newPasswordField;
        
        private int handleChargeFlagField;
        
        private bool handleChargeFlagFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SubscriberNo {
            get {
                return this.subscriberNoField;
            }
            set {
                this.subscriberNoField = value;
                this.RaisePropertyChanged("SubscriberNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string OldPassword {
            get {
                return this.oldPasswordField;
            }
            set {
                this.oldPasswordField = value;
                this.RaisePropertyChanged("OldPassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NewPassword {
            get {
                return this.newPasswordField;
            }
            set {
                this.newPasswordField = value;
                this.RaisePropertyChanged("NewPassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int HandleChargeFlag {
            get {
                return this.handleChargeFlagField;
            }
            set {
                this.handleChargeFlagField = value;
                this.RaisePropertyChanged("HandleChargeFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HandleChargeFlagSpecified {
            get {
                return this.handleChargeFlagFieldSpecified;
            }
            set {
                this.handleChargeFlagFieldSpecified = value;
                this.RaisePropertyChanged("HandleChargeFlagSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.huawei.com/bme/cbsinterface/common")]
    public partial class ResultHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string commandIdField;
        
        private string versionField;
        
        private string transactionIdField;
        
        private string sequenceIdField;
        
        private string resultCodeField;
        
        private string resultDescField;
        
        private System.Nullable<long> orderIdField;
        
        private bool orderIdFieldSpecified;
        
        private string operationTimeField;
        
        private string reserve1Field;
        
        private string reserve2Field;
        
        private string reserve3Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CommandId {
            get {
                return this.commandIdField;
            }
            set {
                this.commandIdField = value;
                this.RaisePropertyChanged("CommandId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
                this.RaisePropertyChanged("TransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SequenceId {
            get {
                return this.sequenceIdField;
            }
            set {
                this.sequenceIdField = value;
                this.RaisePropertyChanged("SequenceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ResultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
                this.RaisePropertyChanged("ResultCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ResultDesc {
            get {
                return this.resultDescField;
            }
            set {
                this.resultDescField = value;
                this.RaisePropertyChanged("ResultDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<long> OrderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
                this.RaisePropertyChanged("OrderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrderIdSpecified {
            get {
                return this.orderIdFieldSpecified;
            }
            set {
                this.orderIdFieldSpecified = value;
                this.RaisePropertyChanged("OrderIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string OperationTime {
            get {
                return this.operationTimeField;
            }
            set {
                this.operationTimeField = value;
                this.RaisePropertyChanged("OperationTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Reserve1 {
            get {
                return this.reserve1Field;
            }
            set {
                this.reserve1Field = value;
                this.RaisePropertyChanged("Reserve1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Reserve2 {
            get {
                return this.reserve2Field;
            }
            set {
                this.reserve2Field = value;
                this.RaisePropertyChanged("Reserve2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Reserve3 {
            get {
                return this.reserve3Field;
            }
            set {
                this.reserve3Field = value;
                this.RaisePropertyChanged("Reserve3");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.huawei.com/bme/cbsinterface/password")]
    public partial class CheckPasswordRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string subscriberNoField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SubscriberNo {
            get {
                return this.subscriberNoField;
            }
            set {
                this.subscriberNoField = value;
                this.RaisePropertyChanged("SubscriberNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.huawei.com/bme/cbsinterface/passwordmgr")]
    public partial class CheckPasswordResultMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultHeader resultHeaderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultHeader ResultHeader {
            get {
                return this.resultHeaderField;
            }
            set {
                this.resultHeaderField = value;
                this.RaisePropertyChanged("ResultHeader");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckPasswordRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.huawei.com/bme/cbsinterface/passwordmgr", Order=0)]
        public HSAPI.PasswordMgrService.CheckPasswordRequestMsg CheckPasswordRequestMsg;
        
        public CheckPasswordRequest1() {
        }
        
        public CheckPasswordRequest1(HSAPI.PasswordMgrService.CheckPasswordRequestMsg CheckPasswordRequestMsg) {
            this.CheckPasswordRequestMsg = CheckPasswordRequestMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.huawei.com/bme/cbsinterface/passwordmgr", Order=0)]
        public HSAPI.PasswordMgrService.CheckPasswordResultMsg CheckPasswordResultMsg;
        
        public CheckPasswordResponse() {
        }
        
        public CheckPasswordResponse(HSAPI.PasswordMgrService.CheckPasswordResultMsg CheckPasswordResultMsg) {
            this.CheckPasswordResultMsg = CheckPasswordResultMsg;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.huawei.com/bme/cbsinterface/passwordmgr")]
    public partial class ChangePasswordRequestMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RequestHeader requestHeaderField;
        
        private ChangePasswordRequest changePasswordRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public RequestHeader RequestHeader {
            get {
                return this.requestHeaderField;
            }
            set {
                this.requestHeaderField = value;
                this.RaisePropertyChanged("RequestHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ChangePasswordRequest ChangePasswordRequest {
            get {
                return this.changePasswordRequestField;
            }
            set {
                this.changePasswordRequestField = value;
                this.RaisePropertyChanged("ChangePasswordRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.huawei.com/bme/cbsinterface/passwordmgr")]
    public partial class ChangePasswordResultMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultHeader resultHeaderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultHeader ResultHeader {
            get {
                return this.resultHeaderField;
            }
            set {
                this.resultHeaderField = value;
                this.RaisePropertyChanged("ResultHeader");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePasswordRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.huawei.com/bme/cbsinterface/passwordmgr", Order=0)]
        public HSAPI.PasswordMgrService.ChangePasswordRequestMsg ChangePasswordRequestMsg;
        
        public ChangePasswordRequest1() {
        }
        
        public ChangePasswordRequest1(HSAPI.PasswordMgrService.ChangePasswordRequestMsg ChangePasswordRequestMsg) {
            this.ChangePasswordRequestMsg = ChangePasswordRequestMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.huawei.com/bme/cbsinterface/passwordmgr", Order=0)]
        public HSAPI.PasswordMgrService.ChangePasswordResultMsg ChangePasswordResultMsg;
        
        public ChangePasswordResponse() {
        }
        
        public ChangePasswordResponse(HSAPI.PasswordMgrService.ChangePasswordResultMsg ChangePasswordResultMsg) {
            this.ChangePasswordResultMsg = ChangePasswordResultMsg;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.huawei.com/bme/cbsinterface/passwordmgr")]
    public partial class ResetPasswordRequestMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RequestHeader requestHeaderField;
        
        private ResetPasswordRequest resetPasswordRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public RequestHeader RequestHeader {
            get {
                return this.requestHeaderField;
            }
            set {
                this.requestHeaderField = value;
                this.RaisePropertyChanged("RequestHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ResetPasswordRequest ResetPasswordRequest {
            get {
                return this.resetPasswordRequestField;
            }
            set {
                this.resetPasswordRequestField = value;
                this.RaisePropertyChanged("ResetPasswordRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.huawei.com/bme/cbsinterface/passwordmgr")]
    public partial class ResetPasswordResultMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultHeader resultHeaderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultHeader ResultHeader {
            get {
                return this.resultHeaderField;
            }
            set {
                this.resultHeaderField = value;
                this.RaisePropertyChanged("ResultHeader");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResetPasswordRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.huawei.com/bme/cbsinterface/passwordmgr", Order=0)]
        public HSAPI.PasswordMgrService.ResetPasswordRequestMsg ResetPasswordRequestMsg;
        
        public ResetPasswordRequest1() {
        }
        
        public ResetPasswordRequest1(HSAPI.PasswordMgrService.ResetPasswordRequestMsg ResetPasswordRequestMsg) {
            this.ResetPasswordRequestMsg = ResetPasswordRequestMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResetPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.huawei.com/bme/cbsinterface/passwordmgr", Order=0)]
        public HSAPI.PasswordMgrService.ResetPasswordResultMsg ResetPasswordResultMsg;
        
        public ResetPasswordResponse() {
        }
        
        public ResetPasswordResponse(HSAPI.PasswordMgrService.ResetPasswordResultMsg ResetPasswordResultMsg) {
            this.ResetPasswordResultMsg = ResetPasswordResultMsg;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.huawei.com/bme/cbsinterface/passwordmgr")]
    public partial class CheckOperatorPasswordRequestMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RequestHeader requestHeaderField;
        
        private CheckOperatorPasswordRequest resetPasswordRequestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public RequestHeader RequestHeader {
            get {
                return this.requestHeaderField;
            }
            set {
                this.requestHeaderField = value;
                this.RaisePropertyChanged("RequestHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public CheckOperatorPasswordRequest ResetPasswordRequest {
            get {
                return this.resetPasswordRequestField;
            }
            set {
                this.resetPasswordRequestField = value;
                this.RaisePropertyChanged("ResetPasswordRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.huawei.com/bme/cbsinterface/passwordmgr")]
    public partial class CheckOperatorPasswordResultMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultHeader resultHeaderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResultHeader ResultHeader {
            get {
                return this.resultHeaderField;
            }
            set {
                this.resultHeaderField = value;
                this.RaisePropertyChanged("ResultHeader");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckOperatorPasswordRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.huawei.com/bme/cbsinterface/passwordmgr", Order=0)]
        public HSAPI.PasswordMgrService.CheckOperatorPasswordRequestMsg CheckOperatorPasswordRequestMsg;
        
        public CheckOperatorPasswordRequest1() {
        }
        
        public CheckOperatorPasswordRequest1(HSAPI.PasswordMgrService.CheckOperatorPasswordRequestMsg CheckOperatorPasswordRequestMsg) {
            this.CheckOperatorPasswordRequestMsg = CheckOperatorPasswordRequestMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckOperatorPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.huawei.com/bme/cbsinterface/passwordmgr", Order=0)]
        public HSAPI.PasswordMgrService.CheckOperatorPasswordResultMsg CheckOperatorPasswordResultMsg;
        
        public CheckOperatorPasswordResponse() {
        }
        
        public CheckOperatorPasswordResponse(HSAPI.PasswordMgrService.CheckOperatorPasswordResultMsg CheckOperatorPasswordResultMsg) {
            this.CheckOperatorPasswordResultMsg = CheckOperatorPasswordResultMsg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PasswordChannel : HSAPI.PasswordMgrService.Password, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PasswordClient : System.ServiceModel.ClientBase<HSAPI.PasswordMgrService.Password>, HSAPI.PasswordMgrService.Password {
        
        public PasswordClient() {
        }
        
        public PasswordClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PasswordClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PasswordClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PasswordClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HSAPI.PasswordMgrService.CheckPasswordResponse HSAPI.PasswordMgrService.Password.CheckPassword(HSAPI.PasswordMgrService.CheckPasswordRequest1 request) {
            return base.Channel.CheckPassword(request);
        }
        
        public HSAPI.PasswordMgrService.CheckPasswordResultMsg CheckPassword(HSAPI.PasswordMgrService.CheckPasswordRequestMsg CheckPasswordRequestMsg) {
            HSAPI.PasswordMgrService.CheckPasswordRequest1 inValue = new HSAPI.PasswordMgrService.CheckPasswordRequest1();
            inValue.CheckPasswordRequestMsg = CheckPasswordRequestMsg;
            HSAPI.PasswordMgrService.CheckPasswordResponse retVal = ((HSAPI.PasswordMgrService.Password)(this)).CheckPassword(inValue);
            return retVal.CheckPasswordResultMsg;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HSAPI.PasswordMgrService.CheckPasswordResponse> HSAPI.PasswordMgrService.Password.CheckPasswordAsync(HSAPI.PasswordMgrService.CheckPasswordRequest1 request) {
            return base.Channel.CheckPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<HSAPI.PasswordMgrService.CheckPasswordResponse> CheckPasswordAsync(HSAPI.PasswordMgrService.CheckPasswordRequestMsg CheckPasswordRequestMsg) {
            HSAPI.PasswordMgrService.CheckPasswordRequest1 inValue = new HSAPI.PasswordMgrService.CheckPasswordRequest1();
            inValue.CheckPasswordRequestMsg = CheckPasswordRequestMsg;
            return ((HSAPI.PasswordMgrService.Password)(this)).CheckPasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HSAPI.PasswordMgrService.ChangePasswordResponse HSAPI.PasswordMgrService.Password.ChangePassword(HSAPI.PasswordMgrService.ChangePasswordRequest1 request) {
            return base.Channel.ChangePassword(request);
        }
        
        public HSAPI.PasswordMgrService.ChangePasswordResultMsg ChangePassword(HSAPI.PasswordMgrService.ChangePasswordRequestMsg ChangePasswordRequestMsg) {
            HSAPI.PasswordMgrService.ChangePasswordRequest1 inValue = new HSAPI.PasswordMgrService.ChangePasswordRequest1();
            inValue.ChangePasswordRequestMsg = ChangePasswordRequestMsg;
            HSAPI.PasswordMgrService.ChangePasswordResponse retVal = ((HSAPI.PasswordMgrService.Password)(this)).ChangePassword(inValue);
            return retVal.ChangePasswordResultMsg;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HSAPI.PasswordMgrService.ChangePasswordResponse> HSAPI.PasswordMgrService.Password.ChangePasswordAsync(HSAPI.PasswordMgrService.ChangePasswordRequest1 request) {
            return base.Channel.ChangePasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<HSAPI.PasswordMgrService.ChangePasswordResponse> ChangePasswordAsync(HSAPI.PasswordMgrService.ChangePasswordRequestMsg ChangePasswordRequestMsg) {
            HSAPI.PasswordMgrService.ChangePasswordRequest1 inValue = new HSAPI.PasswordMgrService.ChangePasswordRequest1();
            inValue.ChangePasswordRequestMsg = ChangePasswordRequestMsg;
            return ((HSAPI.PasswordMgrService.Password)(this)).ChangePasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HSAPI.PasswordMgrService.ResetPasswordResponse HSAPI.PasswordMgrService.Password.ResetPassword(HSAPI.PasswordMgrService.ResetPasswordRequest1 request) {
            return base.Channel.ResetPassword(request);
        }
        
        public HSAPI.PasswordMgrService.ResetPasswordResultMsg ResetPassword(HSAPI.PasswordMgrService.ResetPasswordRequestMsg ResetPasswordRequestMsg) {
            HSAPI.PasswordMgrService.ResetPasswordRequest1 inValue = new HSAPI.PasswordMgrService.ResetPasswordRequest1();
            inValue.ResetPasswordRequestMsg = ResetPasswordRequestMsg;
            HSAPI.PasswordMgrService.ResetPasswordResponse retVal = ((HSAPI.PasswordMgrService.Password)(this)).ResetPassword(inValue);
            return retVal.ResetPasswordResultMsg;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HSAPI.PasswordMgrService.ResetPasswordResponse> HSAPI.PasswordMgrService.Password.ResetPasswordAsync(HSAPI.PasswordMgrService.ResetPasswordRequest1 request) {
            return base.Channel.ResetPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<HSAPI.PasswordMgrService.ResetPasswordResponse> ResetPasswordAsync(HSAPI.PasswordMgrService.ResetPasswordRequestMsg ResetPasswordRequestMsg) {
            HSAPI.PasswordMgrService.ResetPasswordRequest1 inValue = new HSAPI.PasswordMgrService.ResetPasswordRequest1();
            inValue.ResetPasswordRequestMsg = ResetPasswordRequestMsg;
            return ((HSAPI.PasswordMgrService.Password)(this)).ResetPasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HSAPI.PasswordMgrService.CheckOperatorPasswordResponse HSAPI.PasswordMgrService.Password.CheckOperatorPassword(HSAPI.PasswordMgrService.CheckOperatorPasswordRequest1 request) {
            return base.Channel.CheckOperatorPassword(request);
        }
        
        public HSAPI.PasswordMgrService.CheckOperatorPasswordResultMsg CheckOperatorPassword(HSAPI.PasswordMgrService.CheckOperatorPasswordRequestMsg CheckOperatorPasswordRequestMsg) {
            HSAPI.PasswordMgrService.CheckOperatorPasswordRequest1 inValue = new HSAPI.PasswordMgrService.CheckOperatorPasswordRequest1();
            inValue.CheckOperatorPasswordRequestMsg = CheckOperatorPasswordRequestMsg;
            HSAPI.PasswordMgrService.CheckOperatorPasswordResponse retVal = ((HSAPI.PasswordMgrService.Password)(this)).CheckOperatorPassword(inValue);
            return retVal.CheckOperatorPasswordResultMsg;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HSAPI.PasswordMgrService.CheckOperatorPasswordResponse> HSAPI.PasswordMgrService.Password.CheckOperatorPasswordAsync(HSAPI.PasswordMgrService.CheckOperatorPasswordRequest1 request) {
            return base.Channel.CheckOperatorPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<HSAPI.PasswordMgrService.CheckOperatorPasswordResponse> CheckOperatorPasswordAsync(HSAPI.PasswordMgrService.CheckOperatorPasswordRequestMsg CheckOperatorPasswordRequestMsg) {
            HSAPI.PasswordMgrService.CheckOperatorPasswordRequest1 inValue = new HSAPI.PasswordMgrService.CheckOperatorPasswordRequest1();
            inValue.CheckOperatorPasswordRequestMsg = CheckOperatorPasswordRequestMsg;
            return ((HSAPI.PasswordMgrService.Password)(this)).CheckOperatorPasswordAsync(inValue);
        }
    }
}
